# Generated by Django 3.2.12 on 2022-02-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=200)),
                ('employment_type', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='employee')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
